#!/usr/bin/bash

. /usr/share/ppz/bash.functions

espeak-wrapper-harsh() {
	 espeak -s 200 "$@" 2>/dev/null
}

espeak-wrapper-soft() {
	 mm --end=0.05 /usr/share/sounds/alsa/Noise.wav &>/dev/null
}

espeak-wrapper() {
	 espeak-wrapper-harsh "$@"
	 echo -n $(date)"     "
	 echo_yellow "$@"
}

echo $(date)"     $1"

sleep 30

espeak-wrapper "thirty seconds"

for number in one two three four five six seven eight nine ten \
	 eleven twelve thirteen fourteen fifteen sixteen seventeen eighteen nineteen twenty; do
	 sleep 30
	 espeak-wrapper "$number minutes"
	 sleep 30
	 espeak-wrapper "$number minutes thirty seconds"
done
